var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                           xxxx                 ",
   "                                                   xxxx                         ",
   "                                                         ss          s          ",
   "                                                   o     xx       xxxxxxx       ",
   "                                            x    xxxxxxxxx                   o  ",
   "                                      o xx                               xxxxxx ",
   "              o      s       o       xx                                         ",
   "          xxxxxxx   xxx    xxxx  xx                                             ",
   "      @                                                                         ",
   "xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",                                  
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                          ",
   "                                                                                x                         ",
   "                                                                                x                         ",
   "                                                                                x                         ",
   "                                                                                x                         ",
   "                                                                                x                         ",
   "                                                                                x          xxx            ",
   "                                                                                x     =      x = x  x  =  ",
   "                                                                                x     o      x   x  x     ",
   "                                                                      x   =     x     x      x   x  x     ",
   "                                                                  s   xx        xx           x            ",
   "                    xx  x    x     x     x       xx            xxxxxx x         x     =      x            ",
   "                        |    |     |     |                            x         x     o     xx            ",
   "                                                        xxxxx         x         x     x      x    xx      ",
   "                                                    s   xxxxx         x        xx            x            ",
   "                                                   xxxx xxxxx         x         x            x  x  =  x   ",
   "                                              o    xxxx xxxxx         xx        x x          x            ",
   "                                      o       xxxx xxxx xxxxx         x        ox     =      xx    o    x ",
   "       @   s                        xxxxx     xxxx xxxx xxxxx         x   =     x     o     xx            ",
   "     xxxxxxxx                       xxxxxx    xxxx xxxx xxxxx         x        xx     x     x   x  =  x   ",
   "     xxxxxxxx                       xxxxxx    xxxx xxxx xxxxx         xo        xx          x      o      ",
   "     xxxxxxxx                  xxx  xxxxxx    xxxx xxxx xxxxx         x         x           x    xxxxx    ",
   "     xxxxxxxx        |s        xxx  xxxxxx    xxxx xxxx xxxxx         x   =     x     xxxxxx              ",
   "     xxxxxxxx   xx   xxxx      xxx  xxxxxx    xxxx xxxx xxxxx         xx              xxxxxx              ",
   "     xxxxxxxx   xx   xxxx   xx xxx  xxxxxx    xxxx xxxx xxxxx                         xxxxxx              ",
   "     xxxxxxxx   xx   xxxx   xx xxx  xxxxxx    xxxx xxxx xxxxx              xxxxxxxx   xxxxxx              ",
   "!!!!!xxxxxxxx!!!xx!!!xxxx!!!xx!xxx!!xxxxxx!!!!xxxx!xxxx!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                          "],
  ["                                                                   ",
   "                                                                   ",
   "                                                                   ",
   "                                                                   ",
   "                                                                   ",                         
   "                                                                   ",
   "                sss  ssss  sssosss                                 ",
   "      xx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x     x           ",
   "  x                                         x         ox           ",                                                                    
   "  x                                         x         xx           ",
   "  xx   |                                    x     =    x           ",
   "  x                                         x          x           ",
   "  x                                         xo         x           ",
   "  xxxxxx    s    o  s                x      xx         x           ",
   "           xxx  xxx x x  xxxxxx      x      x    xx   ox           ",                                                                    
   "                                     x      x         xx           ",
   "                                  xxxx      x          x           ",
   "                                            x    =     x           ",
   "                     x  x  x  x x           x          x           ",
   "           o      xx    x     x             x          x           ",
   "         xxxxx    xx    x     x             xxxxx xxxxxx           ",
   "     @  xxxxxxx   xx    x     x                                    ",
   "     x  xxxxxxx   xx    x     x                  o                 ",
   "!!!sssssxxxxxxx!!!xx!!!!x!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],  
  ["                                                o    ",                                                                   
   "                       o                             ",
   "                                                     ",
   "                                                     ",
   "                                                     ",
   "                                                     ",
   "                                                     ",
   "                                                     ", 
   "         x     x      xxx       x      x             ",
   "          x   x      x   x      x      x             ",
   "           xxx      x     x     x      x             ",
   "            x       x     x     x      x             ",
   "            x       x     x     x      x             ",
   "            x        x   x       x    x              ",
   "            x         xxx         xxxx       xx      ",
   "                                             xx      ",
   "     x               x   xxxxxxx   xx   x    xx      ",
   "      x             x       x      x x  x    xx      ",
   "       x     x     x        x      x  x x            ",
   "        x  x   x  x         x      x   xx    xx      ",
   "         x      x        xxxxxxx   x    x    xx      ",
   "                                                     ",
   "   @                                                 ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"], 

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;